name: "Mirror to gitlab.gnome.org"

on: [push, delete, create]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.gnome.org:aunetx/blur-my-shell.git
          ssh_private_key:
            ${{ secrets.GIT_MIRROR_SSH_PRIVATE_KEY }}
